version: '3'

services:
  backend:
    build:
      context: ./backend-test
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build:
      context: ./task-manager-frontend
    ports:
      - "3001:80"
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    user: root  # 👈 Add this line
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home:
